### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mandicai** [mandicai/maternity-leave#1]
- [x] Add annotations once data is all in
- [ ] Make box and whisker plot 
- [ ] Maybe ratings? 
- [ ] Add percentage below 12 weeks, percentage above 30 weeks (<-- find out what those exact values are based on the quartile)
- [ ] Manage transitions
