### ISSUE TITLE
future todo (updated)

### ISSUE THREAD

**Issue by mandicai** [mandicai/maternity-leave#2]
- [ ] one day this will be mobile friendly 💪
- [ ] switch to canvas or webGL to improve performance
- [ ] sort by industry
- [x] transition for table, edit text size and colors
- [ ] clean up duplicate code 
- [x] use d3.size() to get count of elements
- [x] scatterplot or add concrete numbers for < 10, < 20, < 30, < 40
- [x] add a search bar
- [x] fix opacity of larger and smaller percentages
- [x] mobile friendly (fetch doesn't exist on safari...)
        - move chart to bottom and have the text scroll on the top of the page 

people commented that they would like to see:
- how many people work for each company? --> what percentage of the US population does this represent?
- what percentage of full pay does each company grant as part of "paid maternity leave"?
